//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeProjetosDeFinanciamento
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidades : DbContext
    {
        public Entidades()
            : base("name=Entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bonificacao> Bonificacao { get; set; }
        public virtual DbSet<ComissaoDeFinanciamento> ComissaoDeFinanciamento { get; set; }
        public virtual DbSet<Despacho> Despacho { get; set; }
        public virtual DbSet<DespachoBonificacao> DespachoBonificacao { get; set; }
        public virtual DbSet<DespachoIncentivo> DespachoIncentivo { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<EstadosComissao> EstadosComissao { get; set; }
        public virtual DbSet<EstadosGestor> EstadosGestor { get; set; }
        public virtual DbSet<EstadosTecnico> EstadosTecnico { get; set; }
        public virtual DbSet<GestorDeFinanciamento> GestorDeFinanciamento { get; set; }
        public virtual DbSet<Historico> Historico { get; set; }
        public virtual DbSet<Incentivo> Incentivo { get; set; }
        public virtual DbSet<Pagamento> Pagamento { get; set; }
        public virtual DbSet<ParecerTecnico> ParecerTecnico { get; set; }
        public virtual DbSet<Projeto> Projeto { get; set; }
        public virtual DbSet<Promotor> Promotor { get; set; }
        public virtual DbSet<Responsavel> Responsavel { get; set; }
        public virtual DbSet<Tecnico> Tecnico { get; set; }
        public virtual DbSet<Utilizador> Utilizador { get; set; }
        public virtual DbSet<PedidoDeReforco> PedidoDeReforco { get; set; }
    }
}
