//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeProjetosDeFinanciamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParecerTecnico
    {
        public int id { get; set; }
        public string texto_livre { get; set; }
        public string decisao { get; set; }
        public System.DateTime data_parecer { get; set; }
        public int id_projeto { get; set; }
    
        public virtual Projeto Projeto { get; set; }
    }
}
