//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeProjetosDeFinanciamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoDeReforco
    {
        public int id { get; set; }
        public Nullable<int> id_despacho { get; set; }
        public System.DateTime data_pedido { get; set; }
        public double montante { get; set; }
        public System.DateTime prazo { get; set; }
        public string decisao { get; set; }
    
        public virtual Despacho Despacho { get; set; }
    }
}
