//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorDeProjetosDeFinanciamento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projeto()
        {
            this.Despacho = new HashSet<Despacho>();
            this.Historico = new HashSet<Historico>();
            this.ParecerTecnico = new HashSet<ParecerTecnico>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public System.DateTime data_criacao { get; set; }
        public double montante_solicitado { get; set; }
        public int estado { get; set; }
        public int id_tecnico { get; set; }
        public int id_responsavel { get; set; }
        public int id_promotor { get; set; }
    
        public virtual Bonificacao Bonificacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Despacho> Despacho { get; set; }
        public virtual Estado Estado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historico> Historico { get; set; }
        public virtual Incentivo Incentivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParecerTecnico> ParecerTecnico { get; set; }
        public virtual Promotor Promotor { get; set; }
        public virtual Responsavel Responsavel { get; set; }
        public virtual Tecnico Tecnico { get; set; }
    }
}
